### ISSUE TITLE
Publishing punchlist

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-freshwater-data-publishing-guide#2]
- [x] Cover illustration @javiesgm 
- [x] Copy edit @kcopas (11/2/24: glossary left)
- [x] Add glossary links @kcopas
- [x] Add internal cross-reference links
- [x] Convert coloured cells from Word tables to other formatting
- [x] Adjust column titles?

---

#### last paragraph 1.1:
- [x] glossary benthic: @Jen: I think this needs to be re-written, maybe as "refers to the ecological region at the bottom of a water body, such as a lake, river, or ocean." as benthic strictly speaking does not mean organisms....
> Agreed. I suggest, "Term referring to the ecological region at the bottom of a water body (such as a lake, river, or ocean) or a wetland. Also used to refer to organisms that live on the bottom of a body of water or wetland, whether on or in the substrate."
- [x] "as detailed below" can refer to section 1.2.3

#### 1.1.1:
- [x] first: "(as described below)" can be deleted (corresponds to the GitHub issue #3)
- [x] the enumeration of the biomes: the sentence "with groundwater, brackish water, palustrine wetlands, and coastal systems grouped within transitional realms" does not belong to point 3., but should be written below
- [x] I liked our bold keywords in the text to make it easier for skim-readers to find what they are actually looking for; can this be re-introduced? Agreed!
- [x] last paragraph: there is a blank after the comma in "light penetration,oxygen level" missing

#### 1.3.1:
- [x] caption of table includes links to 2.1 and 2.2 which in fact should be 1.1 and 1.2 (as you re-numbered our headlines)

#### 1.3.2:
- [x] Table 3 caption: to my opinion it should be as follows "Terms with freshwater-specific definitions, examples and comments..." as the terms per se are not freshwater-specific
- [x] Table 3 would look nicer if the columns definition and example(s) could be broader and status would be smaller; column example(s) should also be left-aligned
- [x] #7
- [x] for the last two lines the term is missing and and the remaining fields are shifted; and I think our last line is missing

#### 2.1:
- [x] second paragraph: we refer to section two, which is "Specific freshwater data considerations", not to the Introduction - In this document, it should be section 1 (Specific freshwater data considerations, as Astrid noted), as the introduction does not have a section number.

#### 2.1.1:
- [x] Table 4: same for the table caption
- [x] table formatting as above (it "would look nicer if the columns definition and example(s) could be broader and status would be smaller; column example(s) should also be left-aligned")
- [x] line taxonID: I think "for example" in the example-column is not necessary as all these are examples...
- [x] #8 : "in the column example we had further explanations in [] (square brackets): these are sometimes implemented in the table and sometimes replaced by ()"

#### 2.1.2:
- [x] Table 5: same for the table caption
- [x] table formatting as above (it "would look nicer if the columns definition and example(s) could be broader and status would be smaller; column example(s) should also be left-aligned")
- [x] #8 : "in the column example we had further explanations in [] (square brackets): these are sometimes implemented in the table and sometimes replaced by ()"
- [x] in the comment column we sometimes refer to terms (e.g. identificationQualifier); not all of them are linked to DwC in your table

#### 2.1.3:
- [x] second paragraph: I suppose the "microhabitats" should just link to the glossary; no brackets, no blue colour needed
- [x] Table 6: same for the table caption
- [x] table formatting as above (it "would look nicer if the columns definition and example(s) could be broader and status would be smaller; column example(s) should also be left-aligned")
- [x] #8
- [x] in the comment column we sometimes refer to terms (e.g. identificationQualifier); not all of them are linked to DwC in your table
- [x] line sampleSizeValue, column 2: "indivdual": an "i" is missing
- [x] sometimes the full stops at the end of the definitions in column 2 are missing

#### 2.2:
- [x] sentence "We provide examples for the content of the fields, and where necessary, even selection lists to choose from.": as the current tables do not include the term selection lists, we might want to change the wording here
- [x] last paragraph: a bracket after Goedkoop 2022 is missing
- [x] Table 7: according to your general changes line 1, column 2 should start with a capital letter and end with a full stop. Full stops sometimes missing in this column.
- [x] same table comments as above
- [x] #9

#### 3.1:
- [x] The link for paragraph 2.2 goes to paragraph 1.2 

#### 3.2:
- [x] I would appreciate a link to Frehswater Network as suggested in our document; or is there any reason for taking it out?

#### harmonisation issues:
- [x] #11
- [x] "e.g." is sometimes written with and sometimes without a comma after; is there any different meaning in those two?
> It should just be consistent. Technically, there should be a comma after e.g. for grammatical reasons, but as long as this is just done consistently, it should be fine.
 
#### General issue:
- [x] When the text talks about opportunistic, targeted, or assemblage sampling (e.g., second paragraph of 3.1), the word assemblage links to the glossary. But in this context, we actually are talking about the phrase assemblage sampling, which we defined in section 1.2.2. Can the link to the glossary be removed? 
The glossary link should also be removed from 
- [x] the second paragraph of 1.3.1 and 
- [x] the second paragraph of 2.1.2. 
- [x] You could link back to section 1.2.2 in these cases if you wanted to link to a definition for all three terms (opportunistic, targeted, and assemblage sampling)

**Comment by kcopas** [comment]
#### last paragraph 1.1:
- [ ] glossary benthic: @Jen: I think this needs to be re-written, maybe as "refers to the ecological region at the bottom of a water body, such as a lake, river, or ocean." as benthic strictly speaking does not mean organisms....
> Agreed. I suggest, "Term referring to the ecological region at the bottom of a water body (such as a lake, river, or ocean) or a wetland. Also used to refer to organisms that live on the bottom of a body of water or wetland, whether on or in the substrate."
- [ ] "as detailed below" can refer to section 1.2.3

#### 1.1.1:
- [ ] first: "(as described below)" can be deleted (corresponds to the GitHub issue #3)
- [ ] the enumeration of the biomes: the sentence "with groundwater, brackish water, palustrine wetlands, and coastal systems grouped within transitional realms" does not belong to point 3., but should be written below
- [ ] I liked our bold keywords in the text to make it easier for skim-readers to find what they are actually looking for; can this be re-introduced? Agreed!
- [ ] last paragraph: there is a blank after the comma in "light penetration,oxygen level" missing

#### 1.3.1:
- [ ] caption of table includes links to 2.1 and 2.2 which in fact should be 1.1 and 1.2 (as you re-numbered our headlines)

#### 1.3.2:
- [ ] Table 3 caption: to my opinion it should be as follows "Terms with freshwater-specific definitions, examples and comments..." as the terms per se are not freshwater-specific
- [ ] Table 3 would look nicer if the columns definition and example(s) could be broader and status would be smaller; column example(s) should also be left-aligned
- [ ] for the headline we had suggested "freshwater term definition", "freshwater example" etc.
- [ ] for the last two lines the term is missing and and the remaining fields are shifted; and I think our last line is missing

#### 2.1:
- [ ] second paragraph: we refer to section two, which is "Specific freshwater data considerations", not to the Introduction - In this document, it should be section 1 (Specific freshwater data considerations, as Astrid noted), as the introduction does not have a section number.

#### 2.1.1:
- [ ] Table 4: same for the table caption and table formatting as above
- [ ] line taxonID: I think "for example" in the example-column is not necessary as all these are examples...
- [ ] in the column example we had further explanations in [] (square brackets): these are sometimes implemented in the table and sometimes replaced by ()

#### 2.1.2:
- [ ] Table 5: same for the table caption and table formatting as above
- [ ] same for the brackets
- [ ] in the comment column we sometimes refer to terms (e.g. identificationQualifier); not all of them are linked to DwC in your table

#### 2.1.3:
- [ ] second paragraph: I suppose the "microhabitats" should just link to the glossary; no brackets, no blue colour needed
- [ ] Table 6: same for the table caption and table formatting as above
- [ ] same for the brackets and the linking in comments
- [ ] line sampleSizeValue, column 2: "indivdual": an "i" is missing
- [ ] sometimes the full stops at the end of the definitions in column 2 are missing

#### 2.2:
- [ ] sentence "We provide examples for the content of the fields, and where necessary, even selection lists to choose from.": as the current tables do not include the term selection lists, we might want to change the wording here
- [ ] last paragraph: a bracket after Goedkoop 2022 is missing
- [ ] Table 7: according to your general changes line 1, column 2 should start with a capital letter and end with a full stop. Full stops sometimes missing in this column.
- [ ] same table comments as above
- [ ] verbatimElevation lacks the inclusion @Jen

#### 3.1:
- [ ] The link for paragraph 2.2 goes to paragraph 1.2 

#### 3.2:
- [ ] I would appreciate a link to Frehswater Network as suggested in our document; or is there any reason for taking it out?

#### harmonisation issues:
- [ ] should glossary terms be underlined and linked whenever they appear or only the first time they appear? I noted both ways...
- [ ] "e.g." is sometimes written with and sometimes without a comma after; is there any different meaning in those two?
> It should just be consistent. Technically, there should be a comma after e.g. for grammatical reasons, but as long as this is just done consistently, it should be fine.
 
#### General issue:
- [ ] When the text talks about opportunistic, targeted, or assemblage sampling (e.g., second paragraph of 3.1), the word assemblage links to the glossary. But in this context, we actually are talking about the phrase assemblage sampling, which we defined in section 1.2.2. Can the link to the glossary be removed? The glossary link should also be removed from the second paragraph of 1.3.1 and the second paragraph of 2.1.2. You could link back to section 1.2.2 in these cases if you wanted to link to a definition for all three terms (opportunistic, targeted, and assemblage sampling)
